### ISSUE TITLE
Warum ist der Ansagengenerator offline? 

### ISSUE THREAD

**Issue by LariFariBerlin** [MrKrisKrisu/Ansagengenerator-JS#1]
Gestern war er noch da. Ich weiß auch nicht, was ich tun muss um den wieder zum laufen zu bringen. Was ist ein Webroot?

**Comment by user15678** [comment]
Würde mich auch interessieren...🤔

**Comment by BjarneRest** [comment]
Echt komisch
![Galileomystery](https://user-images.githubusercontent.com/8419370/152694146-49121981-e43a-443a-99ac-82674a34558d.jpg)

**Comment by dtamm** [comment]
Zumal auch der Quellcode nicht korrekt / vollständig ist ;)

**Comment by AyranLiebhaber** [comment]
Wann geht die Website wieder online?
